default:
  tags:
    - {{ cookiecutter.project_name }}

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages: {{ cookiecutter._new_line }}
{%- if cookiecutter.stage_eni_review_deploy_system_install -%}
  - eni-review-deploy-system-install
{% endif %}
{%- if cookiecutter.stage_eni_staging_deploy_system_install -%}
  - eni-staging-deploy-system-install
{% endif %}
{%- if cookiecutter.stage_eni_deploy_tools_notebook -%}
  - eni-deploy-tools-notebook
{% endif %}
{%- if cookiecutter.stage_eni_deploy_cucr_cli -%}
  - eni-deploy-cucr-cli
{% endif %}
{%- if cookiecutter.stage_eni_deploy_cucr_gateway -%}
  - eni-deploy-cucr-gateway
{% endif %}
{%- if cookiecutter.stage_eni_deploy_cucr_usecase -%}
  - eni-deploy-cucr-usecase
{% endif %}
{%- if cookiecutter.stage_eni_launch_system_dashboards -%}
  - eni-launch-system-dashboards
{% endif %}
{%- if cookiecutter.stage_eni_launch_customer_portal -%}
- eni-launch-customer-portal
{% endif %}
{%- if cookiecutter.stage_eni_launch_customization -%}
  - eni-launch-customization
{% endif %}
{%- if cookiecutter.stage_eni_sanity_check_worker -%}
  - eni-sanity-check-worker
{% endif %}
{%- if cookiecutter.stage_eni_uninstall -%}
  - eni-uninstall
{% endif %}
{%- if cookiecutter.stage_eni_prod_uninstall -%}
  - eni-prod-uninstall
{% endif %}



include: {{ cookiecutter._new_line }}
{%- if cookiecutter.stage_eni_review_deploy_system_install -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-review-env.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_staging_deploy_system_install -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-staging-env.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_deploy_tools_notebook -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-tools.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_deploy_cucr_cli or cookiecutter.stage_eni_deploy_cucr_gateway -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-cucr.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_deploy_cucr_usecase -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-usecase.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_launch_system_dashboards -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-system-dashboards.gitlab-ci.yaml" 
{% endif %}
{%- if cookiecutter.stage_eni_launch_customer_portal or cookiecutter.stage_eni_launch_customization -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-customization.gitlab-ci.yaml"    
{% endif %}
{%- if cookiecutter.stage_eni_sanity_check_worker -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_uninstall -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-uninstall.gitlab-ci.yaml"
{% endif %}
{%- if cookiecutter.stage_eni_prod_uninstall -%}
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: master
    file: "gitlab-ci/worker-server/eni-deploy-prod-uninstall.gitlab-ci.yaml"
{% endif %}