default:
  tags:
    - {{ cookiecutter.project_name }}

variables:
  GIT_SUBMODULE_STRATEGY: recursive


stages:
  {%- if cookiecutter.stage_eni-review-deploy-system-install -%}
  - eni-review-deploy-system-install
  {% endif %}
  {%- if cookiecutter.stage_eni-staging-deploy-system-install -%}
  - eni-staging-deploy-system-install
  {% endif %}


stages_x:
  - eni-review-deploy-system-install
  - eni-staging-deploy-system-install
  - eni-deploy-tools-notebook
  - eni-deploy-cucr-cli
  - eni-deploy-cucr-gateway
  - eni-deploy-cucr-usecase
  - eni-launch-system-dashboards
  - eni-launch-customer-portal
  - eni-launch-customization
  - eni-sanity-check-worker
  - eni-uninstall
  - eni-prod-uninstall

include_x:
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-review-env.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-staging-env.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-cucr.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-tools.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-usecase.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-system-dashboards.gitlab-ci.yaml" 
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-customization.gitlab-ci.yaml"    
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-uninstall.gitlab-ci.yaml"
  - project: "nia/nia-templates/eni-cicd-assets"
    ref: release/21.Q2
    file: "gitlab-ci/worker-server/eni-deploy-prod-uninstall.gitlab-ci.yaml"

